[project]
name = "ssec-cli"
version = "0.1.0"
description = "A CLI tool built with typer"
authors = ["Your Name <your.email@example.com>"]
channels = ["conda-forge"]
platforms = ["osx-64", "osx-arm64", "linux-64", "win-64"]

[dependencies]
python = ">=3.8"
typer = ">=0.9.0"
rich = "*"
flake8 = "*"

[pypi-dependencies]
ssec-cli = { path = ".", editable = true }

[tasks]
install = "pip install -e ."
dev-install = "pip install -e '.[dev]'"
run = "ssec-cli"
test = "pytest"
lint = "ruff check ."
format = "ruff format ."

[feature.dev.dependencies]
pytest = "*"
ruff = "*"
mypy = "*"
flake8 = "*"

[environments]
dev = ["dev"]
